title: SAM

theme: "just-the-docs"
remote_theme: pmarsceill/just-the-docs

exclude: ["xcode-project/",
          "build/",
          "cling-playground/",
          "cmake-build-debug/",
          "include/",
          "inputs/",
          "outputs/",
          "src/",
          "test/",
          "Testing/",
          "SAM.srctrlprj",  
          "_config.yml",
          "CMakeLists.txt",
          "config_file.json",
          "Doxyfile",
          "hacking_strategies.json",
          "main.cpp",
          "new_researcher_config.json",
          "SAM.srctrlbm",
          "SAM.srctrldb"]



