title: SAM
description: An extensible p-hacking simulator

permalink: pretty
exclude: ["src/", "include/"]


remote_theme: pmarsceill/just-the-docs

# Enable or disable the site search
search_enabled: true