title: SAM
description: An extensible p-hacking simulator

permalink: pretty
exclude: ["src/", "include/", "inputs/", "outputs/"]

remote_theme: pmarsceill/just-the-docs

aux_links:
    "SAM on GitHub":
      - "//github.com/amirmasoudabdol/SAMpp"

# Enable or disable the site search
search_enabled: true