name: macOS

on:
  push:
    branches: [ devel ]

jobs:
  build:

    runs-on: macos-latest

    steps:
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: dependencies
      run: |
        brew tap nlohmann/json
        brew install nlohman-json
        brew install boost 
        brew install armadillo ensmallen mlpack
        brew install fmt spdlog lua

    - name: cmake 
      run: cmake -S . -B build
      
    - name: build
      run: cmake --build build --parallel 10